LEARNING_RATE: 0.0001
BATCH_SIZE: 1
EPOCHS: 1000
TRAIN_CSV_PATH: datasets/color_normals_train_df.csv
TRAIN_COLOR_IMAGES_PATH: color2
TRAIN_DEPTH_IMAGES_PATH: depth2
OPTIMIZER: adam
CRITERION: smoothl1
VALIDATE_EVERY: 500  # run validation on test dataset and save metrics
